name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      # 3. Build JAR and run tests
      - name: Build Spring Boot JAR and run tests
        run: ./gradlew clean bootJar test --no-daemon

      # 4. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          push: true
          tags: dota2classic/highlights
          file: ./Dockerfile
